# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0007_auto_20170304_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('validated', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('reject_reason', models.TextField(blank=True, max_length=400)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shop.Shop')),
            ],
        ),
    ]
