# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170303_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
