# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20170303_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='reject_reason',
            field=models.TextField(blank=True, max_length=400),
        ),
    ]
