# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20170304_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='lat',
            field=models.DecimalField(decimal_places=12, max_digits=16),
        ),
        migrations.AlterField(
            model_name='shop',
            name='lng',
            field=models.DecimalField(decimal_places=12, max_digits=16),
        ),
    ]
