# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170220_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='baseuser',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
