# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20170223_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='photo',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
