# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20170226_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
